"""empty message

Revision ID: 697676896d95
Revises: 
Create Date: 2022-05-02 23:11:52.890901

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '697676896d95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('artist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('playlist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('thumbnail', sa.LargeBinary(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('thumbnail',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hash', sa.String(), nullable=False),
                    sa.Column('data', sa.LargeBinary(), nullable=False),
                    sa.Column('ext', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('song',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('duration', sa.Float(), nullable=True),
                    sa.Column('disabled', sa.Boolean(), nullable=False),
                    sa.Column('extractor', sa.String(), nullable=True),
                    sa.Column('data', sa.LargeBinary(), nullable=True),
                    sa.Column('dataext', sa.String(), nullable=True),
                    sa.Column('weburl', sa.String(), nullable=True),
                    sa.Column('thumb_id', sa.String(), nullable=True),
                    sa.Column('artist_id', sa.Integer(), nullable=True),
                    sa.Column('album_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
                    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
                    sa.ForeignKeyConstraint(['thumb_id'], ['thumbnail.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('weburl')
                    )
    op.create_table('playlist_song',
                    sa.Column('song_id', sa.Integer(), nullable=False),
                    sa.Column('playlist_id', sa.Integer(), nullable=False),
                    sa.Column('dateadded', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
                    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
                    sa.PrimaryKeyConstraint('song_id', 'playlist_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_song')
    op.drop_table('song')
    op.drop_table('user')
    op.drop_table('thumbnail')
    op.drop_table('playlist')
    op.drop_table('artist')
    op.drop_table('album')
    # ### end Alembic commands ###
