"""add extension to song model

Revision ID: ce63d21ad89d
Revises: b832ce4f779b
Create Date: 2022-04-17 14:09:08.993563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce63d21ad89d'
down_revision = 'b832ce4f779b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension', sa.String(), nullable=True))
        batch_op.alter_column('extractor',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Song', schema=None) as batch_op:
        batch_op.alter_column('extractor',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('extension')

    # ### end Alembic commands ###
